language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/Islandora/islandora_bagit.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/cwrc_islandora_bagit
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_bagit sites/all/modules/islandora_bagit
  - drush en --user=1 --yes islandora_basic_collection
  - drush en --yes --user=1 islandora_bagit
  - drush en --yes --user=1 cwrc_islandora_bagit
script:
  - ant -buildfile sites/all/modules/cwrc_islandora_bagit/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/cwrc_islandora_bagit
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer cwrc_islandora_bagit
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/cwrc_islandora_bagit
  - drush test-run --uri=http://localhost:8081 "Islandora BagIt"
notifications:
  irc: "irc.freenode.org#islandora"
